# Generated by Django 5.2.7 on 2025-11-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['route', 'day_of_week', 'departure_time']},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.trip'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relationship',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Guardian'), ('RELATIVE', 'Relative')], default='PARENT', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Guardian'), ('RELATIVE', 'Relative')], default='PARENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='emergency_contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='myapp.vehicle'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('VAN', 'Van'), ('BUS', 'Bus'), ('JEEPNEY', 'Jeepney'), ('COASTER', 'Coaster')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='VehicleLocation',
        ),
    ]
