# Generated by Django 5.2.8 on 2025-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/'),
        ),
    ]
